// build.rs
fn main() {
    // Rerun build script if the generated stub changes
    println!("cargo:rerun-if-changed=../../bin/test-debug.s");
    // Input stub generated by the compiler
    let in_path = "../../bin/test-debug.s";
    
    cc::Build::new()
        .file(in_path) // Patched assembly file
        .compile("test_lib"); // Library name
}
